/**
 * MOCK — replaced by the API client in Phase 1.
 *
 * Believable sample data shaped exactly like `domain-types.ts`. Every page reads
 * the app through the accessor functions at the bottom of this file; in Phase 1
 * those bodies become `apiFetch(...)` calls and nothing else has to change.
 */
import type {
  Account,
  DramaSeries,
  Idea,
  Incident,
  Post,
  ReviewItem,
  Source,
  WorkerTask,
} from './domain-types';

/** Hours/days-from-now helpers keep the mock feeling "live" without a fixed date. */
const HOUR = 3_600_000;
const DAY = 24 * HOUR;
const from = (ms: number) => new Date(Date.now() + ms).toISOString();

export const accounts: Account[] = [
  {
    id: 'mindful-minutes',
    name: 'Mindful Minutes',
    handle: '@mindfulminutes',
    platform: 'YOUTUBE',
    contentType: 'AI',
    connectionMethod: 'OWN_APP',
    dramasEnabled: false,
    avatarUrl: null,
    health: 'HEALTHY',
    connection: 'CONNECTED',
    tokenExpiresAt: from(38 * DAY),
    followers: 184_300,
    views30d: 2_410_000,
    scheduledCount: 6,
    openIncidents: 0,
    monetized: true,
    paused: false,
    createdAt: from(-220 * DAY),
  },
  {
    id: 'viral-clips-daily',
    name: 'Viral Clips Daily',
    handle: '@viralclipsdaily',
    platform: 'YOUTUBE',
    contentType: 'REPURPOSED',
    connectionMethod: 'POSTQUED',
    dramasEnabled: false,
    avatarUrl: null,
    health: 'WARNING',
    connection: 'EXPIRING',
    tokenExpiresAt: from(2 * DAY),
    followers: 92_800,
    views30d: 1_150_000,
    scheduledCount: 11,
    openIncidents: 1,
    monetized: true,
    paused: false,
    createdAt: from(-140 * DAY),
  },
  {
    id: 'daily-recipes',
    name: 'Daily Recipes',
    handle: 'Daily Recipes',
    platform: 'FACEBOOK',
    contentType: 'REPURPOSED',
    connectionMethod: 'OWN_APP',
    dramasEnabled: false,
    avatarUrl: null,
    health: 'HEALTHY',
    connection: 'CONNECTED',
    tokenExpiresAt: from(51 * DAY),
    followers: 47_600,
    views30d: 640_000,
    scheduledCount: 4,
    openIncidents: 0,
    monetized: false,
    paused: false,
    createdAt: from(-90 * DAY),
  },
  {
    id: 'neon-drama-shorts',
    name: 'Neon Drama Shorts',
    handle: '@neondrama',
    platform: 'TIKTOK',
    contentType: 'AI',
    connectionMethod: 'POSTQUED',
    dramasEnabled: true,
    avatarUrl: null,
    health: 'HEALTHY',
    connection: 'CONNECTED',
    tokenExpiresAt: from(29 * DAY),
    followers: 311_500,
    views30d: 5_820_000,
    scheduledCount: 9,
    openIncidents: 0,
    monetized: false,
    paused: false,
    createdAt: from(-70 * DAY),
  },
  {
    id: 'trendy-bytes',
    name: 'Trendy Bytes',
    handle: '@trendybytes',
    platform: 'TIKTOK',
    contentType: 'MIXED',
    connectionMethod: 'POSTQUED',
    dramasEnabled: true,
    avatarUrl: null,
    health: 'CRITICAL',
    connection: 'DISCONNECTED',
    tokenExpiresAt: from(-3 * DAY),
    followers: 128_900,
    views30d: 980_000,
    scheduledCount: 2,
    openIncidents: 2,
    monetized: false,
    paused: true,
    createdAt: from(-55 * DAY),
  },
];

export const posts: Post[] = [
  // Mindful Minutes (AI, YouTube)
  {
    id: 'p1',
    contentItemId: 'p1',
    accountId: 'mindful-minutes',
    title: '5-Minute Morning Reset',
    status: 'PUBLISHED',
    scheduledAt: null,
    publishedAt: from(-2 * DAY),
    views: 84_200,
    accent: 'violet',
  },
  {
    id: 'p2',
    contentItemId: 'p2',
    accountId: 'mindful-minutes',
    title: 'Box Breathing for Focus',
    status: 'SCHEDULED',
    scheduledAt: from(1 * DAY),
    publishedAt: null,
    views: null,
    accent: 'violet',
  },
  {
    id: 'p3',
    contentItemId: 'p3',
    accountId: 'mindful-minutes',
    title: 'Sleep Story: Quiet Coast',
    status: 'SCHEDULED',
    scheduledAt: from(3 * DAY),
    publishedAt: null,
    views: null,
    accent: 'indigo',
  },
  {
    id: 'p4',
    contentItemId: 'p4',
    accountId: 'mindful-minutes',
    title: 'Anxiety Off-Ramp',
    status: 'IN_REVIEW',
    scheduledAt: null,
    publishedAt: null,
    views: null,
    accent: 'amber',
  },
  // Viral Clips Daily (REPURPOSED, YouTube)
  {
    id: 'p5',
    contentItemId: 'p5',
    accountId: 'viral-clips-daily',
    title: 'Top 10 Fails of the Week',
    status: 'PUBLISHED',
    scheduledAt: null,
    publishedAt: from(-1 * DAY),
    views: 41_500,
    accent: 'sky',
  },
  {
    id: 'p6',
    contentItemId: 'p6',
    accountId: 'viral-clips-daily',
    title: 'Street Magician Compilation',
    status: 'FAILED',
    scheduledAt: from(-4 * HOUR),
    publishedAt: null,
    views: null,
    accent: 'red',
  },
  {
    id: 'p7',
    contentItemId: 'p7',
    accountId: 'viral-clips-daily',
    title: 'Satisfying Restores #42',
    status: 'SCHEDULED',
    scheduledAt: from(6 * HOUR),
    publishedAt: null,
    views: null,
    accent: 'sky',
  },
  // Daily Recipes (REPURPOSED, Facebook)
  {
    id: 'p8',
    contentItemId: 'p8',
    accountId: 'daily-recipes',
    title: '15-Minute Garlic Butter Shrimp',
    status: 'PUBLISHED',
    scheduledAt: null,
    publishedAt: from(-6 * HOUR),
    views: 22_800,
    accent: 'sky',
  },
  {
    id: 'p9',
    contentItemId: 'p9',
    accountId: 'daily-recipes',
    title: 'No-Bake Cheesecake Cups',
    status: 'SCHEDULED',
    scheduledAt: from(2 * DAY),
    publishedAt: null,
    views: null,
    accent: 'sky',
  },
  // Neon Drama Shorts (AI, TikTok)
  {
    id: 'p10',
    contentItemId: 'p10',
    accountId: 'neon-drama-shorts',
    title: 'Midnight Heist — Ep. 3',
    status: 'PUBLISHED',
    scheduledAt: null,
    publishedAt: from(-12 * HOUR),
    views: 512_000,
    accent: 'violet',
  },
  {
    id: 'p11',
    contentItemId: 'p11',
    accountId: 'neon-drama-shorts',
    title: 'Midnight Heist — Ep. 4',
    status: 'SCHEDULED',
    scheduledAt: from(18 * HOUR),
    publishedAt: null,
    views: null,
    accent: 'violet',
  },
  {
    id: 'p12',
    contentItemId: 'p12',
    accountId: 'neon-drama-shorts',
    title: 'Neon City B-roll Drop',
    status: 'DRAFT',
    scheduledAt: null,
    publishedAt: null,
    views: null,
    accent: 'zinc',
  },
  // Trendy Bytes (MIXED, TikTok)
  {
    id: 'p13',
    contentItemId: 'p13',
    accountId: 'trendy-bytes',
    title: 'Trend Recap: Week 28',
    status: 'FAILED',
    scheduledAt: from(-1 * DAY),
    publishedAt: null,
    views: null,
    accent: 'red',
  },
  {
    id: 'p14',
    contentItemId: 'p14',
    accountId: 'trendy-bytes',
    title: 'AI Voiceover Test Cut',
    status: 'DRAFT',
    scheduledAt: null,
    publishedAt: null,
    views: null,
    accent: 'zinc',
  },
];

export const reviewItems: ReviewItem[] = [
  {
    id: 'r1',
    accountId: 'viral-clips-daily',
    kind: 'INGESTED_VIDEO',
    title: 'Kuaishou clip — parkour rooftop',
    description: null,
    submittedAt: from(-3 * HOUR),
    status: 'PENDING',
    sourceUrl: 'https://kuaishou.example/v/8812',
    rightsNote: null,
    durationSec: 47,
    sourceVideoId: null,
    hasThumbnail: false,
    scheduledAt: null,
  },
  {
    id: 'r2',
    accountId: 'viral-clips-daily',
    kind: 'INGESTED_VIDEO',
    title: 'Kuaishou clip — kitten vs cucumber',
    description: null,
    submittedAt: from(-5 * HOUR),
    status: 'PENDING',
    sourceUrl: 'https://kuaishou.example/v/8813',
    rightsNote: 'Licensed via SourcePack A',
    durationSec: 32,
    sourceVideoId: null,
    hasThumbnail: false,
    scheduledAt: null,
  },
  {
    id: 'r3',
    accountId: 'daily-recipes',
    kind: 'INGESTED_VIDEO',
    title: 'One-pan pasta short',
    description: null,
    submittedAt: from(-8 * HOUR),
    status: 'PENDING',
    sourceUrl: 'https://kuaishou.example/v/8820',
    rightsNote: null,
    durationSec: 58,
    sourceVideoId: null,
    hasThumbnail: false,
    scheduledAt: null,
  },
  {
    id: 'r4',
    accountId: 'mindful-minutes',
    kind: 'PRODUCED_VIDEO',
    title: 'Anxiety Off-Ramp (final render)',
    description: 'A calm walkthrough of a 90-second reset before your next meeting.',
    submittedAt: from(-2 * HOUR),
    status: 'PENDING',
    sourceUrl: null,
    rightsNote: null,
    durationSec: 312,
    sourceVideoId: null,
    hasThumbnail: true,
    scheduledAt: from(2 * HOUR),
  },
  {
    id: 'r5',
    accountId: 'neon-drama-shorts',
    kind: 'IDEA',
    title: 'Idea: rival crew betrayal arc',
    description: null,
    submittedAt: from(-26 * HOUR),
    status: 'PENDING',
    sourceUrl: null,
    rightsNote: null,
    durationSec: null,
    sourceVideoId: null,
    hasThumbnail: false,
    scheduledAt: null,
  },
  {
    id: 'r6',
    accountId: 'trendy-bytes',
    kind: 'METADATA',
    title: 'Metadata: Trend Recap Week 28',
    description: null,
    submittedAt: from(-30 * HOUR),
    status: 'PENDING',
    sourceUrl: null,
    rightsNote: null,
    durationSec: null,
    sourceVideoId: null,
    hasThumbnail: false,
    scheduledAt: null,
  },
];

export const ideas: Idea[] = [
  {
    id: 'i1',
    accountId: 'mindful-minutes',
    title: 'The 90-second reset for meetings',
    angle: 'Workplace micro-recovery',
    hook: '"Do this before your next call."',
    rationale: 'Competitor "DeskBreak" got 2M views on a similar concept',
    category: 'SIMILAR',
    stage: 'SUGGESTED',
    packageStatus: 'NONE',
    packageStage: null,
    packageStageError: null,
    packageStageLabel: null,
    requestedVideoDurationSec: null,
    requestedClipDurationSec: null,
    rejectionReason: null,
    decidedAt: null,
    viralScore: 82,
    predictedScore: 82,
    createdAt: from(-1 * DAY),
    hasBrief: false,
    hasFinalVideo: false,
    hasThumbnail: false,
    contentItemId: null,
    contentStatus: null,
    scheduledAt: null,
    publishedAt: null,
    voiceoverStatus: null,
    voiceoverReady: false,
    brief: null,
  },
  {
    id: 'i2',
    accountId: 'mindful-minutes',
    title: 'Why your sleep story never lands',
    angle: 'Common mistake explainer',
    hook: '"You are breathing wrong at night."',
    rationale: 'Sleep content trending in wellness niche',
    category: 'RELEVANT',
    stage: 'SUGGESTED',
    packageStatus: 'NONE',
    packageStage: null,
    packageStageError: null,
    packageStageLabel: null,
    requestedVideoDurationSec: null,
    requestedClipDurationSec: null,
    rejectionReason: null,
    decidedAt: null,
    viralScore: 74,
    predictedScore: 74,
    createdAt: from(-2 * DAY),
    hasBrief: false,
    hasFinalVideo: false,
    hasThumbnail: false,
    contentItemId: null,
    contentStatus: null,
    scheduledAt: null,
    publishedAt: null,
    voiceoverStatus: null,
    voiceoverReady: false,
    brief: null,
  },
  {
    id: 'i3',
    accountId: 'mindful-minutes',
    title: 'Cold-start focus ritual',
    angle: 'Routine walkthrough',
    hook: '"3 steps, zero apps."',
    rationale: 'Morning routines consistently outperform in retention',
    category: 'UNIQUE',
    stage: 'IN_PRODUCTION',
    packageStatus: 'READY',
    packageStage: 'READY',
    packageStageError: null,
    packageStageLabel: 'Package ready',
    requestedVideoDurationSec: 60,
    requestedClipDurationSec: 10,
    rejectionReason: null,
    decidedAt: from(-2 * DAY),
    viralScore: 88,
    predictedScore: 88,
    createdAt: from(-3 * DAY),
    hasBrief: true,
    hasFinalVideo: false,
    hasThumbnail: false,
    contentItemId: null,
    contentStatus: null,
    scheduledAt: null,
    publishedAt: null,
    voiceoverStatus: 'READY',
    voiceoverReady: true,
    brief: {
      id: 'b1',
      ideaId: 'i3',
      researchSummary: 'Focus rituals are underexplored',
      storySummary: 'A simple three-step ritual for resetting focus.',
      script: 'Step 1: Ground. Step 2: Breathe. Step 3: Set intention.',
      narrationScript: 'Step 1: Ground. Step 2: Breathe. Step 3: Set intention.',
      englishSummary: '',
      presentationMode: 'voiceover',
      sceneBreakdown: [],
      characterPrompts: [],
      editingInstructions: 'Keep pacing tight, 60s max',
      targetDurationSec: 60,
      videoTitle: 'Cold-start focus ritual',
      videoDescription: 'A 60-second focus reset.',
      thumbnailPrompt: 'Person closing laptop, soft morning light',
      thumbnailNegativePrompt: '',
      universalVideoPrompt: '',
      thumbnailPromptVariants: '',
      voiceoverStatus: 'READY',
      voiceoverReady: true,
      packageStage: 'READY',
      packageStageError: null,
      packageStageLabel: 'Package ready',
      timedTranscript: [],
      transcriptReady: false,
      voiceIdUsed: 'edge:en-US-AriaNeural',
      version: 1,
    },
  },
  {
    id: 'i4',
    accountId: 'mindful-minutes',
    title: 'Breathing pattern for panic',
    angle: 'Emergency tool',
    hook: '"Save this for a bad day."',
    rationale: 'High save-rate potential',
    category: 'RELEVANT',
    stage: 'IN_PRODUCTION',
    packageStatus: 'DONE',
    packageStage: 'READY',
    packageStageError: null,
    packageStageLabel: 'Package ready',
    requestedVideoDurationSec: 45,
    requestedClipDurationSec: 8,
    rejectionReason: null,
    decidedAt: from(-4 * DAY),
    viralScore: 91,
    predictedScore: 91,
    createdAt: from(-5 * DAY),
    hasBrief: true,
    hasFinalVideo: false,
    hasThumbnail: false,
    contentItemId: null,
    contentStatus: null,
    scheduledAt: null,
    publishedAt: null,
    voiceoverStatus: null,
    voiceoverReady: false,
    brief: null,
  },
  {
    id: 'i5',
    accountId: 'mindful-minutes',
    title: 'Evening wind-down in 4 moves',
    angle: 'Nightly routine',
    hook: '"Your phone is keeping you up."',
    rationale: 'Complements sleep content cluster',
    category: 'SIMILAR',
    stage: 'UPLOADED',
    packageStatus: 'DONE',
    packageStage: 'READY',
    packageStageError: null,
    packageStageLabel: 'Package ready',
    requestedVideoDurationSec: 60,
    requestedClipDurationSec: 15,
    rejectionReason: null,
    decidedAt: from(-6 * DAY),
    viralScore: 79,
    predictedScore: 79,
    createdAt: from(-7 * DAY),
    hasBrief: true,
    hasFinalVideo: true,
    hasThumbnail: true,
    contentItemId: 'c5',
    contentStatus: 'SCHEDULED',
    scheduledAt: from(1 * DAY),
    publishedAt: null,
    voiceoverStatus: null,
    voiceoverReady: false,
    brief: null,
  },
  {
    id: 'i6',
    accountId: 'neon-drama-shorts',
    title: 'The double-cross nobody saw',
    angle: 'Cliffhanger series',
    hook: '"He was the informant all along."',
    rationale: 'Plot twists drive shares',
    category: 'UNIQUE',
    stage: 'IN_PRODUCTION',
    packageStatus: 'DONE',
    packageStage: 'READY',
    packageStageError: null,
    packageStageLabel: 'Package ready',
    requestedVideoDurationSec: null,
    requestedClipDurationSec: null,
    rejectionReason: null,
    decidedAt: from(-3 * DAY),
    viralScore: 86,
    predictedScore: 86,
    createdAt: from(-4 * DAY),
    hasBrief: false,
    hasFinalVideo: false,
    hasThumbnail: false,
    contentItemId: null,
    contentStatus: null,
    scheduledAt: null,
    publishedAt: null,
    voiceoverStatus: null,
    voiceoverReady: false,
    brief: null,
  },
  {
    id: 'i7',
    accountId: 'neon-drama-shorts',
    title: 'Origin flashback episode',
    angle: 'Character depth',
    hook: '"Before the heist, there was a promise."',
    rationale: 'Backstory episodes increase series loyalty',
    category: 'SIMILAR',
    stage: 'APPROVED',
    packageStatus: 'NONE',
    packageStage: null,
    packageStageError: null,
    packageStageLabel: null,
    requestedVideoDurationSec: null,
    requestedClipDurationSec: null,
    rejectionReason: null,
    decidedAt: from(-5 * DAY),
    viralScore: 77,
    predictedScore: 77,
    createdAt: from(-6 * DAY),
    hasBrief: false,
    hasFinalVideo: false,
    hasThumbnail: false,
    contentItemId: null,
    contentStatus: null,
    scheduledAt: null,
    publishedAt: null,
    voiceoverStatus: null,
    voiceoverReady: false,
    brief: null,
  },
];

export const sources: Source[] = [
  {
    id: 's1',
    accountId: 'viral-clips-daily',
    type: 'WATCHED_PROFILE',
    url: 'https://kuaishou.example/u/failfactory',
    label: 'FailFactory',
    checkIntervalHours: 6,
    lastCheckedAt: from(-2 * HOUR),
    newItems: 3,
    status: 'ACTIVE',
  },
  {
    id: 's2',
    accountId: 'viral-clips-daily',
    type: 'WATCHED_PROFILE',
    url: 'https://kuaishou.example/u/streetmagic',
    label: 'StreetMagic',
    checkIntervalHours: 12,
    lastCheckedAt: from(-9 * HOUR),
    newItems: 0,
    status: 'ACTIVE',
  },
  {
    id: 's3',
    accountId: 'viral-clips-daily',
    type: 'BULK_IMPORT',
    url: '—',
    label: 'Batch import 2026-07-10',
    checkIntervalHours: 0,
    lastCheckedAt: from(-4 * DAY),
    newItems: 0,
    status: 'PAUSED',
  },
  {
    id: 's4',
    accountId: 'daily-recipes',
    type: 'WATCHED_PROFILE',
    url: 'https://kuaishou.example/u/quickbites',
    label: 'QuickBites',
    checkIntervalHours: 6,
    lastCheckedAt: from(-1 * HOUR),
    newItems: 2,
    status: 'ACTIVE',
  },
  {
    id: 's5',
    accountId: 'daily-recipes',
    type: 'WATCHED_PROFILE',
    url: 'https://kuaishou.example/u/sweettooth',
    label: 'SweetTooth',
    checkIntervalHours: 24,
    lastCheckedAt: from(-20 * HOUR),
    newItems: 0,
    status: 'ERROR',
  },
  {
    id: 's6',
    accountId: 'trendy-bytes',
    type: 'WATCHED_PROFILE',
    url: 'https://kuaishou.example/u/trendwatch',
    label: 'TrendWatch',
    checkIntervalHours: 6,
    lastCheckedAt: from(-3 * DAY),
    newItems: 0,
    status: 'ERROR',
  },
];

export const dramas: DramaSeries[] = [
  {
    id: 'd1',
    accountId: 'neon-drama-shorts',
    title: 'Midnight Heist',
    genre: 'Crime thriller',
    theme: 'Loyalty vs survival',
    audience: 'Young adults',
    episodes: 12,
    producedEpisodes: 4,
    episodeDurationSec: 60,
    seriesBible: null,
    characterSheets: [],
    status: 'IN_PRODUCTION',
    createdAt: from(-30 * DAY),
  },
  {
    id: 'd2',
    accountId: 'neon-drama-shorts',
    title: 'Afterglow',
    genre: 'Sci-fi romance',
    theme: 'Love across timelines',
    audience: 'Gen Z',
    episodes: 8,
    producedEpisodes: 8,
    episodeDurationSec: 90,
    seriesBible: null,
    characterSheets: [],
    status: 'COMPLETE',
    createdAt: from(-60 * DAY),
  },
  {
    id: 'd3',
    accountId: 'neon-drama-shorts',
    title: 'The Quiet Floor',
    genre: 'Psychological',
    theme: 'Office paranoia',
    audience: 'Adults 25-40',
    episodes: 10,
    producedEpisodes: 0,
    episodeDurationSec: 60,
    seriesBible: null,
    characterSheets: [],
    status: 'PLANNING',
    createdAt: from(-3 * DAY),
  },
  {
    id: 'd4',
    accountId: 'trendy-bytes',
    title: 'Loop City',
    genre: 'Time-loop mystery',
    theme: 'Escaping a recursive nightmare',
    audience: 'Sci-fi fans',
    episodes: 6,
    producedEpisodes: 2,
    episodeDurationSec: 120,
    seriesBible: null,
    characterSheets: [],
    status: 'IN_PRODUCTION',
    createdAt: from(-14 * DAY),
  },
];

export const incidents: Incident[] = [
  {
    id: 'inc1',
    accountId: 'viral-clips-daily',
    kind: 'PUBLISH_ERROR',
    severity: 'MEDIUM',
    status: 'OPEN',
    title: 'Upload rejected: duplicate audio track',
    detail:
      'YouTube returned 400 on the publish attempt for "Street Magician Compilation". Item reverted to Draft.',
    retryable: true,
    createdAt: from(-4 * HOUR),
    resolvedAt: null,
  },
  {
    id: 'inc2',
    accountId: 'trendy-bytes',
    kind: 'AUTH',
    severity: 'HIGH',
    status: 'OPEN',
    title: 'PostQued token expired',
    detail: 'Connection dropped; all scheduled posts for this account are halted until re-auth.',
    retryable: false,
    createdAt: from(-3 * DAY),
    resolvedAt: null,
  },
  {
    id: 'inc3',
    accountId: 'trendy-bytes',
    kind: 'COPYRIGHT',
    severity: 'HIGH',
    status: 'OPEN',
    title: 'Copyright claim on "Trend Recap: Week 28"',
    detail: 'Rights holder flagged background music. Item held pending review.',
    retryable: true,
    createdAt: from(-1 * DAY),
    resolvedAt: null,
  },
  {
    id: 'inc4',
    accountId: 'mindful-minutes',
    kind: 'RATE_LIMIT',
    severity: 'LOW',
    status: 'RESOLVED',
    title: 'AI key cooldown during metadata batch',
    detail: 'Provider returned 429; failed over to next key. No content impact.',
    retryable: false,
    createdAt: from(-6 * DAY),
    resolvedAt: from(-6 * DAY + 20 * 60_000),
  },
];

export const tasks: WorkerTask[] = [
  {
    id: 't1',
    accountId: 'mindful-minutes',
    title: 'Edit: Anxiety Off-Ramp final cut',
    assignee: 'Rafael',
    assigneeId: 'u1',
    status: 'IN_PROGRESS',
    assignedAt: from(-1 * DAY),
    uploadedAt: null,
    dueAt: from(1 * DAY),
    briefId: 'b1',
    episodeId: null,
    revisionNotes: [],
  },
  {
    id: 't2',
    accountId: 'neon-drama-shorts',
    title: 'Render: Midnight Heist Ep. 4',
    assignee: 'Mei',
    assigneeId: 'u2',
    status: 'UPLOADED',
    assignedAt: from(-2 * DAY),
    uploadedAt: from(-3 * HOUR),
    dueAt: from(-2 * HOUR),
    briefId: null,
    episodeId: 'e4',
    revisionNotes: [],
  },
  {
    id: 't3',
    accountId: 'neon-drama-shorts',
    title: 'Storyboard: Ep. 5 scene breakdown',
    assignee: 'Mei',
    assigneeId: 'u2',
    status: 'ASSIGNED',
    assignedAt: from(-4 * HOUR),
    uploadedAt: null,
    dueAt: from(2 * DAY),
    briefId: null,
    episodeId: 'e5',
    revisionNotes: [],
  },
  {
    id: 't4',
    accountId: 'viral-clips-daily',
    title: 'Trim + caption: Fails of the Week',
    assignee: 'Diego',
    assigneeId: 'u3',
    status: 'DONE',
    assignedAt: from(-3 * DAY),
    uploadedAt: from(-2 * DAY),
    dueAt: from(-1 * DAY),
    briefId: 'b2',
    episodeId: null,
    revisionNotes: [],
  },
  {
    id: 't5',
    accountId: 'daily-recipes',
    title: 'Voiceover: Garlic Butter Shrimp',
    assignee: 'Rafael',
    assigneeId: 'u1',
    status: 'ASSIGNED',
    assignedAt: from(-5 * HOUR),
    uploadedAt: null,
    dueAt: from(1 * DAY),
    briefId: 'b3',
    episodeId: null,
    revisionNotes: [],
  },
];

// --- Accessors (Phase 1: swap bodies for API calls) ---------------------------

export function getAccounts(): Account[] {
  return accounts;
}

export function getAccount(id: string): Account | undefined {
  return accounts.find((a) => a.id === id);
}

export function getPosts(accountId?: string): Post[] {
  return accountId ? posts.filter((p) => p.accountId === accountId) : posts;
}

export function getReviewItems(
  accountId?: string,
  opts?: { excludeScheduled?: boolean },
): ReviewItem[] {
  let items = accountId ? reviewItems.filter((r) => r.accountId === accountId) : reviewItems;
  // Mirror API excludeScheduled: schedule-approval rows stay on global Review Queue.
  if (opts?.excludeScheduled) {
    items = items.filter((r) => !r.scheduledAt);
  }
  return items;
}

export function getIdeas(accountId?: string): Idea[] {
  return accountId ? ideas.filter((i) => i.accountId === accountId) : ideas;
}

export function getSources(accountId?: string): Source[] {
  return accountId ? sources.filter((s) => s.accountId === accountId) : sources;
}

export function getDramas(accountId?: string): DramaSeries[] {
  return accountId ? dramas.filter((d) => d.accountId === accountId) : dramas;
}

export function getIncidents(accountId?: string): Incident[] {
  return accountId ? incidents.filter((i) => i.accountId === accountId) : incidents;
}

export function getTasks(accountId?: string): WorkerTask[] {
  return accountId ? tasks.filter((t) => t.accountId === accountId) : tasks;
}

/** Cross-account rollups for the global dashboard/analytics pages. */
export function getRollups() {
  const totalFollowers = accounts.reduce((n, a) => n + a.followers, 0);
  const views30d = accounts.reduce((n, a) => n + a.views30d, 0);
  const scheduled = accounts.reduce((n, a) => n + a.scheduledCount, 0);
  const openIncidents = incidents.filter((i) => i.status === 'OPEN').length;
  const pendingReviews = reviewItems.filter((r) => r.status === 'PENDING').length;
  const publishedToday = posts.filter(
    (p) =>
      p.status === 'PUBLISHED' && p.publishedAt && Date.now() - Date.parse(p.publishedAt) < DAY,
  ).length;
  const failed = posts.filter((p) => p.status === 'FAILED').length;
  return {
    totalFollowers,
    views30d,
    scheduled,
    openIncidents,
    pendingReviews,
    publishedToday,
    failed,
    accountCount: accounts.length,
  };
}
